### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'tf'

### ISSUE THREAD

**Issue by mikkokotila** [keras-team/keras#13244]
This started to appear today in automated tests: 

```
Traceback (most recent call last):
  File "./test_script.py", line 14, in <module>
    test_rest(scan_object)
  File "/home/travis/build/autonomio/talos/test/commands/test_rest.py", line 65, in test_rest
    talos.utils.gpu_utils.parallel_gpu_jobs()
  File "/home/travis/build/autonomio/talos/talos/utils/gpu_utils.py", line 15, in parallel_gpu_jobs
    gpu_options = K.tf.GPUOptions(allow_growth=allow_growth,
AttributeError: module 'keras.backend' has no attribute 'tf'
The command "coverage run --source=talos ./test_script.py" exited with 1.
```
Full details [here](https://travis-ci.org/autonomio/talos/jobs/576422673). 

The same tests run ok on my local machine, so I'm assuming something to do with the latest changes to Keras. The relevant part of the code have not been changed in many months, during which period the tests have run ~100 times locally and on Travis.

**Comment by mikkokotila** [comment]
In the meantime, the obvious way to overcome this is by replacing `K.tf.GPUOptions(allow_growth=allow_growth)` with `tf.GPUOptions(allow_growth=allow_growth)` as `keras.backend` just seems to inherit `tf` from TensorFlow.

**Comment by Cstyler** [comment]
What's the problem with `import tensorflow as tf`?

**Comment by brianmanderson** [comment]
I'm having this problem while trying to load in previously created models from keras, I tried converting everything to use tf.compat.v1.keras(...), but that left me with a problem very similar to this one: 
https://github.com/keras-team/keras/issues/10907 
where I get the error 'Node' object has no attribute 'output_masks'

**Comment by mikkokotila** [comment]
@Cstyler There  is no problem, but I don't think it's a support issue. When a software starts to throw an error where in the past it didn't, it's generally considered a bug.

**Comment by brianmanderson** [comment]
Work around was to replace tf.device('/gpu:0') with the new call 


```
if tf.__version__ == '1.14.0':
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus: # Restrict TensorFlow to only use the first GPU
        try:
            tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
            logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        except:
            xxx = 1`
```

**Comment by RayOfSunshine** [comment]
I also encountered this problem, 'keras==2.2.5', but when I change 'keras==2.2.5 to keras==2.2.4', this error "AttributeError: module 'keras.backend' has no attribute 'tf'" has fixed.

**Comment by JustinhoCHN** [comment]
same problem here, keras version: 2.3.1
I was exporting keras model to tf serving:
```
with tf.keras.backend.get_session() as sess:
    tf.saved_model.simple_save(
        sess,
        export_path,
        inputs={'input_image': model.input},
        outputs={t.name:t for t in model.outputs})
```
error raised:
```
AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'get_session'
```

**Comment by danipolo** [comment]
any news on this? same problem here.

**Comment by teacookies1031** [comment]
> I also encountered this problem, 'keras==2.2.5', but when I change 'keras==2.2.5 to keras==2.2.4', this error "AttributeError: module 'keras.backend' has no attribute 'tf'" has fixed.

I fixed by this. Thanks!

**Comment by priyanshgupta1998** [comment]
i also got the same error With Tensorflow==2.1.0 
then  i used 
` session = tf.compat.v1.keras.backend.get_session()`
it works fine

**Comment by ZYG151541155** [comment]
> > I also encountered this problem, 'keras==2.2.5', but when I change 'keras==2.2.5 to keras==2.2.4', this error "AttributeError: module 'keras.backend' has no attribute 'tf'" has fixed.
> 
> I fixed by this. Thanks!

Thia reply can fixed my problem too, Thump up!

**Comment by mfoglio** [comment]
> keras==2.2.4

What is your TensorFlow version? Using keras 2.2.4 doesn't solve

**Comment by XingYu131** [comment]
tensorflow-gpu==1.15.0
keras==2.3.1
keras-bert==0.80.0
keras-transformer==0.30.0

How to slove this problem?

**Comment by JoyceKirkland** [comment]
> I also encountered this problem, 'keras==2.2.5', but when I change 'keras==2.2.5 to keras==2.2.4', this error "AttributeError: module 'keras.backend' has no attribute 'tf'" has fixed.

thank you!it's work for me!!!!

**Comment by NIKHIL12344444** [comment]
iam getting a error related to this please assist
AttributeError: module 'keras.src.backend' has no attribute 'convert_to_numpy'


![Uploading 2024-02-25 (2).png…]()

**Comment by mthompson89** [comment]
I had the same error as @NIKHIL12344444  not sure how to fix it as this github thread is the only place I have seen this error on the internet.

**Comment by weebao** [comment]
Same here
