### ISSUE TITLE
v2.1.5 throws TypeError: on code that worked in 2.1.4 

### ISSUE THREAD

**Issue by chrisrb10** [keras-team/keras#9645]
I have some keras transfer learning and fine-tuning code which was working fine (and still works fine) with 2.1.4, but throws an error with 2.1.5.

Error is:
`TypeError: unsupported operand type(s) for /=: 'JpegImageFile' and 'float'`

The problematic line seems to be the following:
```
history_tl = model.fit_generator(
            train_generator,
            epochs=nb_epoch,
            steps_per_epoch=steps_per_epoch,
            validation_data=validation_generator,
            validation_steps=validation_steps,
            class_weight=None) 
```

steps_per_epoch and validation_steps are calculated as:
```
    steps_per_epoch = nb_train_samples / batch_size
    validation_steps = nb_val_samples / batch_size
```

and the train_generator & validation_generator are created with the following:
```
    # data prep
    print('Running data prep - train')
    train_datagen =  ImageDataGenerator(
        preprocessing_function=preprocess_input,
        rotation_range=30,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True
        )

    print('Running data prep - test')
    test_datagen = ImageDataGenerator(
        preprocessing_function=preprocess_input,
        rotation_range=30,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True
        )

    print('Running data gen - train')
    train_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=(IM_HEIGHT, IM_WIDTH),
        batch_size=batch_size
        )

    print('Running data gen - test')
    validation_generator = test_datagen.flow_from_directory(
        val_dir,
        target_size=(IM_HEIGHT, IM_WIDTH),
        batch_size=batch_size
        )
```

Can you shed any light on what has changed that will cause this code to cease working, and what I need to to do fix it?

Full traceback below.
```
Epoch 1/1
Traceback (most recent call last):
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/preprocessing/image.py", line 825, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/preprocessing/image.py", line 1233, in _get_batches_of_transformed_samples
    img = self.image_data_generator.preprocessing_function(img)
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/applications/inception_v3.py", line 407, in preprocess_input
    return imagenet_utils.preprocess_input(x, mode='tf')
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/applications/imagenet_utils.py", line 178, in preprocess_input
    mode=mode)
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/applications/imagenet_utils.py", line 115, in _preprocess_symbolic_input
    x /= 127.5
TypeError: unsupported operand type(s) for /=: 'JpegImageFile' and 'float'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "nested_inception.py", line 183, in <module>
    train('./data/model_data/', nb_epoch=1)
  File "nested_inception.py", line 154, in train
    class_weight=None) 
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/chris_r_brake/anaconda3/envs/keras_2/lib/python3.6/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: unsupported operand type(s) for /=: 'JpegImageFile' and 'float'
```

**Comment by Dref360** [comment]
The fix is currently in a PR, sorry for that

**Comment by chrisrb10** [comment]
Thanks for the response - I'll stick with 2.1.4 for now.

**Comment by x0v** [comment]
@chrisrb10 Hey chris
I am too stuck in similar problem and continuing with keras=2.1.4
But can you tell how can we pass `mode='tf'` as a param in `preprocessing_function` arg of `ImageDataGenerator` function ?

**Comment by chrisrb10** [comment]
Hi @x0v,
As far as I understand it, the function 'preprocess_input' is imported from the `keras.applications.inception_v3` module - so by definition it is operating with tensorflow (I think).
it works fine for me with no arguments for `preprocess_input`

**Comment by x0v** [comment]
Actually I was talking about this `from keras.applications.vgg16 import preprocess_input`
and when i checked the function definition of preprocess_input, it was not tensorflow by default.

Not sure about Inception though.

**Comment by Dref360** [comment]
This is fixed on master. We reverted the PR that cause this issue.

**Comment by x0v** [comment]
ok thanks @Dref360.

Can any one tell me what difference will these two implementation create ?

1. When i use `preprocess_input` with lambda layer just after initialization 
```
model = Sequential()
model.add(Lambda(preprocess_input, name='preprocessing', input_shape=(224, 224, 3)))
model.add(vgg_conv)
```

2.  While if i don't put a lambda layer at initialization of model and use `preprocess_input` in `ImageDataGenerator` instead ?
```
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    preprocessing_function = preprocess_input
    )
```

**Comment by Dref360** [comment]
As you can see in `ImageDataGenerator.standardize` the preprocessing function is called **before** the rescale. So you won't get the same result.

**Comment by 00krishna** [comment]
This issue should be reopened. I am still running into this problem on Keras 2.1.5. When I down rev'd to 2.1.4, it works fine. So the removal of that PR does not seem to have fixed the issue. Just wanted to let you know.

**Comment by bobbyhaliwela** [comment]
Agreed. This issue should be reopened. Still having this issue on Keras 2.1.5. Thanks

**Comment by Dref360** [comment]
We rarely do hotfixes, please update to the latest version.

**Comment by bobbyhaliwela** [comment]
Agreed. This issue should be reopened. Running into this issue on Keras 2.1.5 so i revert back to 2.1.4 and it works.

**Comment by shravan-rams** [comment]
```
from keras.applications import xception

def preprocess_input_new(x):
    img = xception.preprocess_input(img_to_array(x))
    return array_to_img(img)

ImageDataGenerator(
      preprocessing_function=preprocess_input_new,
      rotation_range=30,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True
  )
```

This will surely help you

**Comment by maxwellmckinnon** [comment]
@shravan-rams -- thank you so much! Now working on Keras 2.1.5

**Comment by omrivm** [comment]
I have the same issue on 2.1.2. I would like to keep using this version. 
@Dref360  can you share what is needed to be fixed?
